version: '3.8'

services:
  ResultBase:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=ResultBase
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
      - ./backend/ResultBase.sql:/docker-entrypoint-initdb.d/ResultBase.sql
    command: --bind-address=0.0.0.0 --init-file /docker-entrypoint-initdb.d/ResultBase.sql

  node-server:
    depends_on:
      - ResultBase
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=ResultBase
      - DB_PASSWORD=
      - DB_NAME=ResultBase
      - DB_USER=root
      - DB_PORT=3306
      - FRONTEND_URL=http://localhost:3000
      - EMAIL_PASSWORD=
      - EMAIL_USER=

  react-app:
    depends_on:
      - node-server
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes: 
  db:
